version: "3"

services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always
    ports:
      - '443:443'

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    networks:
      - inception
    volumes:
      - wp_nginx_volume:/var/www/wordpress
    restart: always
    env_file:
      - .env
    ports:
      - '9000:9000'
    depends_on:
      - mariadb

  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    networks:
      - inception
    volumes:
      - db_volume:/var/lib/mysql
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"

volumes:
  db_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/arohmann/data/db_volume'
  wp_nginx_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/arohmann/data/wp_nginx_volume'

networks:
  inception: